### GET request to example server
GET {{baseUrl}}

###


###
POST {{baseUrl}}/register
Content-Type: application/json

{
    "email": "user@email.com",
    "name": "exampleuser",
    "password": "password123"
}

###
